### ISSUE TITLE
Depreciation

### ISSUE THREAD

**Issue by abdelhak-hiit** [theofidry/AliceDataFixtures#119]
Hello @theofidry ,we have this notice about the `getConfigTreeBuilder` method of the file `Fidry\AliceDataFixtures\Bridge\Symfony\DependencyInjection\Configuration`.

`A tree builder without a root node is deprecated since Symfony 4.2 and will not be supported anymore in 5.0.`

**Comment by pierrejolly** [comment]
Already fixed by #112

**Comment by theofidry** [comment]
Closing since already fixed; The release will be coming when I'm confident in the next version state

**Comment by alcalyn** [comment]
Hi, just to notice that I'm getting this deprecation notice

**Comment by tacman** [comment]
> The release will be coming when I'm confident in the next version state

I'm still getting the deprecation notice, what's the status of the next release?

**Comment by theofidry** [comment]
Most of the pending issues should somehow be merged before the next release :) Since I don't have dedicated time for it, it's entirely up to contributors
